language: scala
scala:
  - 2.13.10
jdk:
  - openjdk17
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
script: 
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test doc assembly
branches:
  only:
    - main
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
