language: scala
scala:
  - 2.12.8
jdk:
  - openjdk10
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script: 
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test doc
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
branches:
  only:
    - master
