#!/usr/bin/env ruby

config_file = File.join(Dir.home, ".apidoc/config")

data = {}
in_default = false
IO.readlines(config_file).map(&:strip).each do |l|
  next if l.empty?

  if in_default
    if l.match(/^\[/)
      in_default = false
      break
    end
    key, value = l.split("=", 2).map(&:strip)
    if !key.empty? && !value.empty?
      data[key.to_sym] = value
    end
    
  elsif l == "[default]"
    in_default = true
  end
end

commands = {
  "APIDOC_API_HOST" => data[:api_uri],
  "APIDOC_API_TOKEN" => data[:token]
}.select { |key, value| !value.to_s.empty? }.map { |key, value| "%s=%s" % [key, value] }.sort

commands << "sbt"

cmd = commands.join(" ")
puts cmd
system(cmd)

