name: auto-merge

on:
  status:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: >-
      ${{ github.event.state == 'success' &&
      (github.event.context == 'continuous-integration/jenkins/pr-head' ||
       github.event.context == 'continuous-integration/jenkins/pr-merge') }}
    uses: flowcommerce/code-steward/.github/workflows/auto-merge.yml@main
    with:
      sha: ${{ github.event.sha }}
    secrets: inherit

